# Generated by Django 4.2.4 on 2023-08-26 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/post_files/'),
        ),
        migrations.AddField(
            model_name='post',
            name='pictures',
            field=models.ImageField(blank=True, null=True, upload_to='media/post_files/'),
        ),
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='media/post_files/'),
        ),
    ]
