# Generated by Django 4.2.4 on 2023-08-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post_file_post_pictures_post_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='pictures',
        ),
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='media/post_images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='media/post_videos/'),
        ),
    ]
