# Generated by Django 4.2.4 on 2023-08-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_post_pictures_post_images_alter_post_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='responses_sum',
            field=models.SmallIntegerField(default=0),
        ),
    ]
