# Generated by Django 4.2.4 on 2023-08-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='type',
            field=models.CharField(choices=[('IM', 'Картинка'), ('VI', 'Видео'), ('FI', 'Файл')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
