# Generated by Django 4.2.4 on 2023-09-02 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_profile_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='responses_sum',
        ),
    ]
