# Generated by Django 4.2.4 on 2023-09-05 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_post_responses_sum'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
